### ISSUE TITLE
How can I remove the additional break lines?

### ISSUE THREAD

**Issue by oimos** [jsonchou/cssCompact#1]
Hi, thank you for the awesome plugin.
I want to know if it is possible to remove the line breaking.
For example, 

> h1{font-size:10px}
> 
> h2{font-size:20px}

I want to output the above 

> h1{font-size:10px}
> h2{font-size:20px}

Thank you.

**Comment by jsonchou** [comment]
@stoneshower 
Hi，
this additional blank lines is a special feature on purpose.
this blank lines depends on your initial code way. you can leave every blank lines as you want.

~~~ css
/* global */
html { box-sizing: border-box; } 

*, 
*::before, 
*::after { box-sizing: inherit; } 


/* ui */
.ui-confirm .ok { color: #0f27a2 } 
.ui-loading { opacity: 0 } 
.ui-loading-on { opacity: 1 } 

/* module */
.md-pop .tit { margin-right: 10px; } 
.md-pop .cnt { margin-right: 10px; } 

/* pages A*/
.pg-a .hd { margin-right: 10px; } 
.pg-a .bd { margin-right: 10px; } 

/* pages B*/
.pg-b .hd { margin-right: 10px; } 
.pg-b .bd { margin-right: 10px; }
~~~

this blank lines split your code into several parts for a good vision.

maybe you can try this sass-compact plugin for your scss files:
[sass-compact](https://marketplace.visualstudio.com/items?itemName=jsonchou.sass-compact)

**Comment by oimos** [comment]
@jsonchou 

Thank you for answering my question. I understand.
I'm gonna the sass-compact plugin.
Thanks!
