### ISSUE TITLE
Customize keyboard shortcut

### ISSUE THREAD

**Issue by ghost** [jsonchou/cssCompact#2]
Hello,

Nice plugin for a better CSS overview. Will never understand why this is not the main syntax for this language, but it's another debate. ^^

I wonder if you could make the keyboard shortcut editable in settings ? I'm not a huge fan of the default shift + alt + f one.

Thank you

Alex

**Comment by jsonchou** [comment]
@PubliAlex 

{
    "key": "**shift+alt+f**",
    "command": "extension.cssCompact",
    "when": "editorTextFocus && editorLangId == 'css'"
}

### method 1
get your vscode keybindings.json file
change the key as you wish

### method 2
command + k, command + s, you can change every extension's key as you can.
